# Configuración para API Gateway
# Configuration for API Gateway

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - AuthenticationFilter
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway

jwt:
  secret: ${JWT_SECRET:bWljcm9jb21tZXJjZS1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LWNoYW5nZS1pbi1wcm9kdWN0aW9u}

